### PR TITLE
Compatibility fixes for iOS <= 7.0

### PR DESCRIPTION
**Pull request by schmidt9**
Some compatibility fixes for iOS <= 7.0 (tested with left view and leftPresentViewOnTop = NO)

### CODE REVIEW

**Comment by schmidt9** [comment]
In my apps I target iOS 6.0, that's why these fixes for backward compatibility, they can be optional since using Categories

**Comment by schmidt9** [comment]
well bugs found, should fix them :)

**Comment by iDevelopper** [comment]
What bugs did you find?

**Comment by schmidt9** [comment]
In my pull request
`// since 7.0
+ (void)animateWithDuration:(NSTimeInterval)duration delay:(NSTimeInterval)delay usingSpringWithDamping:(CGFloat)dampingRatio initialSpringVelocity:(CGFloat)velocity options:(UIViewAnimationOptions)options animations:(void (^)(void))animations completion:(void (^ __nullable)(BOOL finished))completion
{
    if ([UIView respondsToSelector:@selector(animateWithDuration:delay:usingSpringWithDamping:initialSpringVelocity:options:animations:completion:)]) {
        [UIView animateWithDuration:duration delay:delay usingSpringWithDamping:dampingRatio initialSpringVelocity:velocity options:options animations:animations completion:completion];
    } else {
        // since 4.0
        [self animateWithDuration:duration delay:delay options:options animations:animations completion:completion];
    }
}`

**Comment by schmidt9** [comment]
In my pull request this override produces recursion
`+ (void)animateWithDuration:(NSTimeInterval)duration delay:(NSTimeInterval)delay usingSpringWithDamping:(CGFloat)dampingRatio initialSpringVelocity:(CGFloat)velocity options:(UIViewAnimationOptions)options animations:(void (^)(void))animations completion:(void (^ __nullable)(BOOL finished))completion
{
    if ([UIView respondsToSelector:@selector(animateWithDuration:delay:usingSpringWithDamping:initialSpringVelocity:options:animations:completion:)]) {
        [UIView animateWithDuration:duration delay:delay usingSpringWithDamping:dampingRatio initialSpringVelocity:velocity options:options animations:animations completion:completion];
    } else {
        // since 4.0
        [self animateWithDuration:duration delay:delay options:options animations:animations completion:completion];
    }
}`

**Comment by iDevelopper** [comment]
Why did you close this pull request? I can't merge it. I am not a specialist of Github, can you tell me more? Ah this is because you found a bug in your pull request. I did not understand!

**Comment by schmidt9** [comment]
Because I must elaborate aforementioned error with recursion in my code. Problem is how to call this method in UIView's Category, because if it responds to selector, we must call it itself, what leads to recursiin

**Comment by schmidt9** [comment]
Full code you can see in tab "Files changed", formatting in ugly for ObjC code here

**Comment by iDevelopper** [comment]
I can do the class compatible with iOS 6 directly without category, it will are simple?

**Comment by schmidt9** [comment]
Yes, it would be great

**Comment by iDevelopper** [comment]
1) UIVisualEffectView, UIBlurEffect, UIVibrancyEffect (since iOS 8): Do you need this? It is the more difficult to implement, I think!

2) UIViewControllerAnimatedTransitioning, UIViewControllerContextTransitioning (since iOS 7) ? 
I'm not going to implement this feature if iOS <= iOS7.

3) UIView: 
animationWithDuration:delay:usingSpringWithDamping:initialSpringVelocity:options:animations:completion: (since iOS 7): OK, it's easy to replace that with UIView animationWithDuration:delay:options:animations:completion: if iOS <= iOS 7.

4) UIViewController:
willTransitionToSize:withTransitionCoordinator: (since iOS 8): I do not remember very well how the rotation was managed with iOS 6: (willAnimateRotationToInterfaceOrientation:duration: ???)

5) What do you think of this?

**Comment by schmidt9** [comment]
I agree with your proposals. I personally don't need effects, only animation I use is `animationWithDuration:delay:options:animations:completion`, I even don't use rotation currently, so if you implement basic iOS 6 support (I mean at least that code not crashes because of unknown selectors) it will be great

**Comment by schmidt9** [comment]
Also I have some troubles with vertical positioning of menu. But here I'm going to open a separate issue with screenshots

**Comment by iDevelopper** [comment]
I can't test on iOS 6, xCode 5 cannot be run on El Capitan. I have no device on iOS 6 ?? How do you do?

**Comment by schmidt9** [comment]
I have iPhone 4 with iOS 6, so I can test

**Comment by iDevelopper** [comment]
Great!  👍

**Pull request closed without merging**
